import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import type { Bridge } from '../bridge.js';
import { bridgeCall, tabSpecSchema, actionObservationSchema } from './helpers.js';
export function registerAdvancedTools(mcp: McpServer, bridge: Bridge) {
  mcp.registerTool('press_key', { description: 'Send trusted key input to a tab without switching tabs. Optionally focus a selector first. Keys: Enter, Tab, Escape, ArrowDown/Up/Left/Right, Backspace, Delete, Home, End, Space or a single character. Modifiers bitmask: Alt=1, Control=2, Meta=4, Shift=8. Main frame only.', inputSchema: { ...tabSpecSchema, ...actionObservationSchema, key:z.string().min(1), selector:z.string().optional(), modifiers:z.number().int().min(0).max(15).optional() } }, args => bridgeCall(bridge,'interact.pressKey',args));
  mcp.registerTool('select_option', { description: 'Select by exact text from an open dropdown, scrolling the option into view. Scope selector to the listbox/popper; optionSelector defaults to [role=option],li. For native select, selector targets the select and value or text identifies one option. Hidden options and ambiguous matches are rejected.', inputSchema:{ ...tabSpecSchema,...actionObservationSchema,selector:z.string().optional(),text:z.string().optional(),value:z.string().optional(),optionSelector:z.string().optional() } }, args=>bridgeCall(bridge,'interact.selectOption',args));
  const timeout=z.number().int().min(1).max(60000).optional().describe('Timeout in milliseconds, default 10000; maximum 60000.');
  mcp.registerTool('wait_for_text',{description:'Wait for visible rendered text in a selector scope or document body, without dumping the page.',inputSchema:{...tabSpecSchema,text:z.string().min(1),selector:z.string().optional(),exact:z.boolean().optional(),timeout}},args=>bridgeCall(bridge,'browser.wait',{...args,kind:'text'}));
  mcp.registerTool('wait_for_url',{description:'Wait for the target URL to contain the supplied string, or match exactly. Supports SPA URL changes.',inputSchema:{...tabSpecSchema,url:z.string().min(1),exact:z.boolean().optional(),timeout}},args=>bridgeCall(bridge,'browser.wait',{...args,kind:'url'}));
  mcp.registerTool('wait_for_network_idle',{description:'Wait until observed HTTP requests settle for quietMs (default 500). WebSocket/EventSource are excluded. Long polling may prevent idle; prefer text/URL readiness. Starts monitoring on first debugger attachment; earlier requests may be unobserved.',inputSchema:{...tabSpecSchema,quietMs:z.number().int().min(100).max(5000).optional(),timeout}},args=>bridgeCall(bridge,'browser.wait',{...args,kind:'networkIdle'}));
  mcp.registerTool('read_element_state',{description:'Bounded read-only DOM state, including hidden inputs, value, selectedIndex, checked, readonly and selected attributes. Password values are redacted. Does not evaluate arbitrary JavaScript or component methods.',inputSchema:{...tabSpecSchema,selector:z.string().min(1),attributes:z.array(z.string().min(1).max(80)).max(20).optional(),maxChars:z.number().int().min(100).max(4000).optional()}},args=>bridgeCall(bridge,'content.readState',args));
  mcp.registerTool('get_tab_health',{description:'Probe tab responsiveness and queue/deadline status even while another action is stuck. recoverDebugger=true reattaches only when the tab queue is idle; never replays actions. Inspect state after BRIDGE_TIMEOUT before resuming mutations.',inputSchema:{...tabSpecSchema,recoverDebugger:z.boolean().optional()}},args=>bridgeCall(bridge,'browser.health',args));
}
